### ISSUE TITLE
Description on how to use playground does not yield a working example

### ISSUE THREAD

**Issue by rowild** [anncwb/vite-plugin-html#14]
Changing into the playground directory and running `yarn serve` does not work. One reason being that it probably should read `yarn dev`, because there is no `serve` script. But running `yarn dev` throws a ton of errors...

Can you please check and provide a better step-by-step instruction on how to use the playground? Thank you!

**Comment by anncwb** [comment]
My mistake, you should first execute `yarn` to install dependencies, and then execute:
```
cd packages/playground
yarn dev
```
