### ISSUE TITLE
Minifier removes CSP hashes from @vite/plugin-legacy

### ISSUE THREAD

**Issue by reynotekoppele** [anncwb/vite-plugin-html#18]
By adding enabling the minifier the CSP hashes set by [@vite/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) are being removed.

Issue seems te go away by setting `minifyJS` to `false`, though this results in hydration issues as far as I've tested.

Repo with issue can be found at [Git Repo](https://github.com/reynotekoppele/vite-ssr-csp-issue). Is a clone of [Playground SSR Vue](https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue) with slight changes to show the issue.

Headers are added in server.js via [Helmet](https://github.com/helmetjs/helmet).

**To reproduce:**
1. Download repo
2. Run `npm install`
3. Run `npm run build`
4. Run `npm run serve` -> See console for issue
5. Change `minifyJs: true` to `minifyJs: false` in vite.config.js
6. Repeat step 3 and 4

**Comment by anncwb** [comment]
closed c77a0b8ef28ede170c8f5065666c33f319f6b489
