### ISSUE TITLE
yarn add fails of missing installed packages

### ISSUE THREAD

**Issue by Chris2011** [anncwb/vite-plugin-html#7]
I can't install the dependency, due to the missing package is-ci that will be called. Sure I can install it by my own, but maybe it should be a direct dependency of your plugin or it should be somewhere documented that I need to install it too. So I would suggest, that it will be a direct dep in your plugin. IMHO.

Also husky couldn't be found so maybe there is a problem with Windows?

```
error C:\Projekte\Others\smth\node_modules\vite-plugin-html: Command failed.
Exit code: 1
Command: npm run install:husky
Arguments:
Directory: C:\Projekte\Others\smth\node_modules\vite-plugin-html
Output:
> vite-plugin-html@2.0.4 install:husky
> is-ci || husky install

Der Befehl "is-ci" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "husky" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code 1
npm ERR! path C:\Projekte\Others\smth\node_modules\vite-plugin-html
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c is-ci || husky install

npm ERR! A complete log of this run can be found in:
```

Translation: The command `is-ci` couldn't be found or is wrong. Also for husky

Windows 10 64 bit, latest version.
Node 14.16.0 and NPM 7.5.2

**Comment by anncwb** [comment]
Can be solved by upgrading to 2.0.6

**Comment by Chris2011** [comment]
Thx, but I'm a bit confused. Latest version on your github release packages is 2.0.3 and on npmjs.com it is 2.0.4. I installed it via vite-plugin-html@2.0.6. That worked. Thx.

**Comment by ciyucapa** [comment]
npm install npm@latest -g intenta esto!
