### ISSUE TITLE
Dev server fails to start when EJS is used in index.html 

### ISSUE THREAD

**Issue by Esardes** [anncwb/vite-plugin-html#9]
I have the same issue described [there](https://github.com/vitejs/vite/issues/2451) by @yurique
He already created an example repo to reproduce

```
git clone git@github.com:yurique/vite-html-plugin-bug.git
cd vite-html-plugin-bug
yarn
yarn dev
```

**Comment by anncwb** [comment]
I think it should not be possible to write like this. Before Vite starts, it will scan the src of the script tag, then optimize the esm, and then perform the html conversion (the plug-in starts to work at this step), so you can’t meet this writing

**Comment by yurique** [comment]
Is there a better way to specify the js depending on whether it's a dev build or prod build?

**Comment by Esardes** [comment]
closing this ticket since it's not an issue with the plugin

@yurique I ended up doing something like [this](https://github.com/vitejs/vite/issues/678) (in your setup it would mean hardcoding or templating the path to target/scalaversion/.../optOrFastopt  in two separate html files)
